name: Auto Version Bump

on:
  pull_request:
    types: [opened, closed]
    branches: [main]

jobs:
  bump-version:
    if: |
      github.event.action == 'opened' && 
      github.event.pull_request.user.login == 'dependabot[bot]'
    uses: oneminch/workflows/version-bump.yml@v1
    permissions:
      contents: write
    with:
      node-version: "22"
      version-type: patch
  
  push-tags:
    if: |
      github.event.action == 'closed' && 
      github.event.pull_request.merged == true && 
      github.event.pull_request.user.login == 'dependabot[bot]'
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      
      - name: Push tags
        run: git push --follow-tags
